---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-postgres-pv 
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
   - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: localdisk
  local:
    path: /mnt/zabbix/postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - slave

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zabbix-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: localdisk
